### ISSUE TITLE
More than 4 topics with Or

### ISSUE THREAD

**Issue by sagarchapara** [KarimElghamry/Codeforces-Randomizer#16]
Hey it is really awesome website, thanks for making this. 

If possible can you also add a ability to use more than 4 topics with or.

Something like this

![image](https://github.com/KarimElghamry/Codeforces-Randomizer/assets/35074365/6323eebb-9678-4ead-8b34-d907d100999f)

**Comment by KarimElghamry** [comment]
Hi @sagarchapara , thanks for your feedback. I've opened a PR #17 to add an `AND` and `OR` options when selecting the topics. Also, I've removed the max 4 topics limit. The code isn't prettiest, but it gets the job done. I'll deploy once the PR is merged.

**Comment by KarimElghamry** [comment]
@sagarchapara webapp deployed at: https://karimelghamry.github.io/Codeforces-Randomizer/. let me know if it works for you.
